pages:
  image: node:22
  script:
    - corepack enable
    - yarn install --frozen-lockfile
    - yarn lint
    - yarn check:encoding
    - yarn test:unit --run
    - VITE_BASE_URL=/reyohoho/ yarn build
    - rm -rf ./public
    - mkdir ./public
    - cp -r ./dist/* ./public/
  artifacts:
    paths:
      - public
  only:
    - vue
