query FoldersMobilePersonFolderListByProfileId(
  $userProfileId: UserProfileIdInput!
  $personId: Long!
  $offset: Int!
  $limit: Int!
) {
  userProfileById(id: $userProfileId) {
    __typename
    ...foldersMobilePersonFolderListFragment
  }
}

fragment foldersMobilePersonFolderListFragment on UserProfile {
  userData {
    personFolders(limit: $limit, offset: $offset) {
      offset
      limit
      total
      items {
        typeId
        name
        containsPerson(personId: $personId)
        public
        persons {
          total
        }
      }
    }
  }
}
