query HomeConfiguration(
  $lightTargetingInput: TargetingInput!
  $darkTargetingInput: TargetingInput!
) {
  configuration: layoutByTargeting(targeting: $lightTargetingInput) {
    __typename
    ...configurationFragment
  }
  darkConfiguration: layoutByTargeting(targeting: $darkTargetingInput) {
    __typename
    ...darkConfigurationFragment
  }
}

fragment hexColorFragment on HexColor {
  a
  hex
}

fragment gradientFragment on Gradient {
  __typename
  colors {
    hexColor {
      __typename
      ...hexColorFragment
    }
    location
  }
  ... on LinearGradient {
    angle
  }
  ... on RadialGradient {
    relativeCenter {
      x
      y
    }
    relativeRadius {
      x
      y
    }
  }
}

fragment colorFragment on Colors {
  value {
    __typename
    ... on GradientColor {
      gradient {
        __typename
        ...gradientFragment
      }
    }
    ... on HexColor {
      __typename
      ...hexColorFragment
    }
  }
}

fragment configurationOverlayFragment on Overlay {
  text
  shape
  textColor
  textColors {
    __typename
    ...colorFragment
  }
  background {
    color
  }
  attributedText {
    items {
      __typename
      ... on TextProperties {
        name
        text
      }
    }
  }
}

fragment configurationShortcutFragment on Shortcut {
  name
  id
  textStyle {
    color
  }
  background {
    color
    colors {
      __typename
      ...colorFragment
    }
  }
  commonOverlays {
    __typename
    ...configurationOverlayFragment
  }
  actions {
    __typename
    ... on Action {
      backgroundColors {
        __typename
        ...colorFragment
      }
      silent
      subscriptionButtonType
      subscriptionProductFeatures
      subscriptionProductTarget
      subscriptionPaymentMethod
      subscriptionWidgetType
      acquisitionPlatformSubscriptionProperties {
        page
        places
        restrictions
      }
    }
  }
}

fragment configurationSectionFragment on Section {
  metaShortcuts(weightType: LIGHTWEIGHT_ONLY, targeting: $lightTargetingInput) {
    __typename
    ...configurationShortcutFragment
  }
  shortcuts(weightType: LIGHTWEIGHT_ONLY, targeting: $lightTargetingInput) {
    __typename
    ...configurationShortcutFragment
  }
  viewType
}

fragment configurationFragment on Layout {
  sectionGroups {
    sections {
      __typename
      ...configurationSectionFragment
    }
  }
}

fragment darkConfigurationOverlayFragment on Overlay {
  shape
  textColor
  textColors {
    __typename
    ...colorFragment
  }
  background {
    color
  }
}

fragment darkConfigurationShortcutFragment on Shortcut {
  textStyle {
    color
  }
  background {
    color
    colors {
      __typename
      ...colorFragment
    }
  }
  commonOverlays {
    __typename
    ...darkConfigurationOverlayFragment
  }
  actions {
    __typename
    ... on Action {
      backgroundColors {
        __typename
        ...colorFragment
      }
    }
  }
}

fragment darkConfigurationSectionFragment on Section {
  metaShortcuts(weightType: LIGHTWEIGHT_ONLY, targeting: $darkTargetingInput) {
    __typename
    ...darkConfigurationShortcutFragment
  }
  viewType
}

fragment darkConfigurationFragment on Layout {
  sectionGroups {
    sections {
      __typename
      ...darkConfigurationSectionFragment
    }
  }
}
