query Invoice($id: ID!) {
  externalInvoice(id: $id) {
    __typename
    ...invoice
  }
}

fragment invoicePrice on Price {
  currency
  amount
}

fragment invoicePayment on Payment {
  id
  respCode
  respDesc
  status
}

fragment invoice on Invoice {
  id
  invoiceStatus
  form
  paymentMethodId
  paidAmount {
    __typename
    ...invoicePrice
  }
  payment {
    __typename
    ...invoicePayment
  }
  totalAmount {
    __typename
    ...invoicePrice
  }
  invoicePollingParams {
    retryDelayMillis
    timeoutMillis
  }
  widgetQrCodeParams {
    widgetUrl
    underlineText
  }
}
