query MovieDetailsMobileEditorialPosts(
  $movieId: Long!
  $offset: Int!
  $limit: Int!
) {
  movie(id: $movieId) {
    __typename
    ...movieDetailsMobileEditorialPostsFragment
  }
}

fragment imageFragment on Image {
  avatarsUrl
  fallbackUrl
}

fragment editorialPostFragment on Post {
  id
  title
  coverImage {
    __typename
    ...imageFragment
  }
  thumbImage {
    __typename
    ...imageFragment
  }
  published
  publishedAt
}

fragment movieDetailsMobileEditorialPostsFragment on Movie {
  post(offset: $offset, limit: $limit) {
    offset
    limit
    total
    items {
      __typename
      ...editorialPostFragment
    }
  }
}
