query MovieSeriesStructure(
  $id: Long!
  $isOnlyOnline: Boolean!
  $initialEpisodeId: Long!
  $initialEpisodeContentId: String!
  $includeInitialEpisodeById: Boolean!
  $includeInitialEpisodeByContentId: Boolean!
  $includeInitialNextEpisode: Boolean!
  $mediaBillingTarget: String!
) {
  tvSeries(id: $id) {
    __typename
    ...movieSeriesStructureFragment
    ...movieSeriesNextEpisodeOffsetWithSeasonFragment
      @include(if: $includeInitialNextEpisode)
  }
  initialEpisodeById: episode(id: $initialEpisodeId)
    @include(if: $includeInitialEpisodeById) {
    __typename
    ...movieSeriesEpisodeOffsetWithSeasonFragment
  }
  initialEpisodeByContentId: episodeByContentId(
    contentId: $initialEpisodeContentId
  ) @include(if: $includeInitialEpisodeByContentId) {
    __typename
    ...movieSeriesEpisodeOffsetWithSeasonFragment
  }
}

fragment restrictionFragment on Restriction {
  age
  mpaa
}

fragment titleFragment on Title {
  localized
  original
}

fragment imageFragment on Image {
  avatarsUrl
  fallbackUrl
}

fragment subscriptionOfferOptionFragment on PlusOptionOffer {
  additionText
  description
  name
  title
  text
  option {
    name
  }
  plans {
    __typename
  }
}

fragment subscriptionOfferTariffFragment on PlusTariffOffer {
  additionText
  description
  name
  title
  text
  tariff {
    name
  }
  plans {
    __typename
  }
}

fragment subscriptionOfferCompositeDataFragment on SubscriptionCompositeOffers {
  batchPositionId
  offers {
    compositeOffer {
      forActiveOffers {
        __typename
        ... on PlusOptionOffer {
          __typename
          ...subscriptionOfferOptionFragment
        }
        ... on PlusTariffOffer {
          __typename
          ...subscriptionOfferTariffFragment
        }
      }
      structureType
      tariffOffer {
        __typename
        ...subscriptionOfferTariffFragment
      }
      optionOffers {
        __typename
        ...subscriptionOfferOptionFragment
      }
      positionId
      silentInvoiceAvailable
    }
    customPayload {
      overridedAdditionalText
      overridedText
      overridedTarget
    }
  }
}

fragment watchingRejectionFragment on WatchingRejection {
  details
  reason
}

fragment movieViewOptionPurchasedSubscriptionFragment on ViewOption {
  purchasedSubscriptionTextId
  purchasedSubscriptionName
}

fragment availabilityAnnounceFragment on AvailabilityAnnounce {
  announcePromise
  availabilityDate
  type
}

fragment movieContentPackageFragment on ContentPackage {
  billingFeatureName
}

fragment currencyFragment on Currency {
  symbol
  currencyCode
}

fragment moneyAmountFragment on MoneyAmount {
  amount
  currency {
    __typename
    ...currencyFragment
  }
}

fragment movieViewOptionSummaryFragment on ViewOption {
  __typename
  type
  purchasabilityStatus
  isWatchableOnDeviceInCurrentRegion: isWatchable(
    filter: { anyDevice: false, anyRegion: false }
  )
  subscriptionPurchaseTag
  buttonText
  ...movieViewOptionPurchasedSubscriptionFragment
  availabilityAnnounce {
    __typename
    ...availabilityAnnounceFragment
  }
  contentPackageToBuy {
    __typename
    ...movieContentPackageFragment
  }
  contentPackageToUnfreeze {
    __typename
    ...movieContentPackageFragment
  }
  transactionalPrice {
    __typename
    ...moneyAmountFragment
  }
  transactionalMinimumPrice {
    __typename
    ...moneyAmountFragment
  }
  priceWithTotalDiscount {
    __typename
    ...moneyAmountFragment
  }
  optionMonetizationModels
  watchabilityStatus
  watchabilityExpirationTime
  promotionActionType
  downloadabilityStatus
}

fragment movieSeriesStructureViewOptionFragment on ViewOption {
  __typename
  subscriptionCompositeOffers(mediaBillingTarget: $mediaBillingTarget) {
    __typename
    ...subscriptionOfferCompositeDataFragment
  }
  downloadRejectionReason {
    __typename
    ...watchingRejectionFragment
  }
  ...movieViewOptionSummaryFragment
}

fragment movieSeriesStructureFragment on Series {
  id
  contentId
  restriction {
    __typename
    ...restrictionFragment
  }
  title {
    __typename
    ...titleFragment
  }
  gallery {
    covers {
      horizontal {
        __typename
        ...imageFragment
      }
    }
    logos {
      rightholderForCoverRecommendedTheme
    }
  }
  viewOption {
    __typename
    ...movieSeriesStructureViewOptionFragment
  }
  seasons(isOnlyOnline: $isOnlyOnline, offset: 0, limit: 1000) {
    offset
    limit
    total
    items {
      id
      contentId
      episodes(isOnlyOnline: $isOnlyOnline, offset: 0, limit: 0) {
        total
      }
      episodeGroupings(filter: { onlyOnline: $isOnlyOnline }) {
        from
        offset
        to
      }
      number
    }
  }
}

fragment movieSeriesEpisodeOffsetWithSeasonFragment on Episode {
  id
  contentId
  number
  season {
    number
    offsetInSeries(filter: { onlyOnline: $isOnlyOnline })
  }
  offsetInSeason(filter: { onlyOnline: $isOnlyOnline })
}

fragment movieSeriesNextEpisodeOffsetWithSeasonFragment on Series {
  ott {
    __typename
    ... on Ott_AbstractSeries {
      nextEpisode {
        episode {
          __typename
          ...movieSeriesEpisodeOffsetWithSeasonFragment
        }
      }
    }
  }
}
