query MovieMobileDetailsMovieCollections(
  $movieId: Long!
  $offset: Int!
  $limit: Int!
  $includeMovieListMetaTotal: Boolean! = true
) {
  movie(id: $movieId) {
    movieLists(offset: $offset, limit: $limit) {
      offset
      limit
      total
      items {
        __typename
        ...movieMobileDetailsListFragment
      }
    }
  }
}

fragment imageFragment on Image {
  avatarsUrl
  fallbackUrl
}

fragment movieListMetaBaseFragment on MovieListMeta {
  id
  autoList
  name
  description
  url
  cover {
    __typename
    ...imageFragment
  }
  moviesCount: movies(offset: 0, limit: 0)
    @include(if: $includeMovieListMetaTotal) {
    total
  }
}

fragment movieMobileDetailsListFragment on MovieListRelation {
  position
  movieList {
    __typename
    ...movieListMetaBaseFragment
  }
}
