query PersonSeoMeta($personId: Long!, $bestMoviesLimit: Int = 5) {
  person(id: $personId) {
    ...PersonSeoMeta
    __typename
  }
  webPage {
    ...PersonWebPage
    __typename
  }
}

fragment PersonBestMovies on PagingList_PersonBestMovie {
  items {
    movie {
      id
      title {
        russian
        __typename
      }
      __typename
    }
    __typename
  }
  __typename
}

fragment PersonSeoMeta on Person {
  name
  originalName
  dateOfBirth {
    accuracy
    date
    __typename
  }
  poster {
    avatarsUrl
    fallbackUrl
    __typename
  }
  roles(isCareer: true) {
    items {
      role {
        title {
          russian
          __typename
        }
        slug
        __typename
      }
      __typename
    }
    __typename
  }
  bestFilms: bestMovies(limit: $bestMoviesLimit, type: FILM) {
    ...PersonBestMovies
    __typename
  }
  bestSeries: bestMovies(limit: $bestMoviesLimit, type: SERIES) {
    ...PersonBestMovies
    __typename
  }
  __typename
}

fragment PersonWebPage on WebPageContext {
  kpPersonPage(personId: $personId) {
    htmlMeta {
      openGraph {
        image {
          avatarsUrl
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
  __typename
}
