query Plaque(
  $supportedFeatures: [SupportedFeatureInput!]
  $existingPlaques: [ExistingPlaqueInput!]
  $sizeHint: Int
  $targetingInput: TargetingInput!
) {
  plaque: plaque(
    plaqueInput: {
      supportedFeatures: $supportedFeatures
      existingPlaques: $existingPlaques
      sizeHint: $sizeHint
    }
    targeting: $targetingInput
  ) {
    __typename
    ...plaqueDefinitions
  }
}

fragment plaqueContentDescription on ContentDescription {
  text
  templates
  actionText
  accessibilityEnabled
}

fragment strictPlaqueAction on StrictCrossAction {
  __typename
  ... on DeeplinkCrossAction {
    deeplink
  }
  ... on ServiceSpecificCrossAction {
    type
    params {
      key
      value
    }
  }
  ... on JustInteractCrossAction {
    __typename
  }
}

fragment plaqueIndent on IndentRules {
  indentLeft
  indentRight
  indentTop
  indentBottom
}

fragment plaqueColor on Color {
  color
  opacity
  position
}

fragment plaquePoint on Point {
  x
  y
}

fragment plaqueLinearGradient on LinearColorSettings {
  colors {
    __typename
    ...plaqueColor
  }
  startPoint {
    __typename
    ...plaquePoint
  }
  endPoint {
    __typename
    ...plaquePoint
  }
}

fragment plaqueRadialGradient on RadialColorSettings {
  colors {
    __typename
    ...plaqueColor
  }
  centralPoint {
    __typename
    ...plaquePoint
  }
}

fragment plaqueColorSettings on ColorSettings {
  type
  linear {
    __typename
    ...plaqueLinearGradient
  }
  radial {
    __typename
    ...plaqueRadialGradient
  }
}

fragment plaqueCorner on CornerSettings {
  type
  heightFix
}

fragment plaqueShapeSettings on ShapeSettings {
  leftTopCorner {
    __typename
    ...plaqueCorner
  }
  rightTopCorner {
    __typename
    ...plaqueCorner
  }
  leftBottomCorner {
    __typename
    ...plaqueCorner
  }
  rightBottomCorner {
    __typename
    ...plaqueCorner
  }
}

fragment plaqueDisplayRules on DisplayRules {
  indentRules {
    __typename
    ...plaqueIndent
  }
  backgroundColorSettings {
    __typename
    ...plaqueColorSettings
  }
  backgroundShapeSettings {
    __typename
    ...plaqueShapeSettings
  }
}

fragment plaqueWidgetRules on DisplayWidgetRules {
  displayRules {
    __typename
    ...plaqueDisplayRules
  }
  opacity
  horizontalRule
  verticalRule
  widthFix
  widthType
}

fragment plaqueTextProperty on TaxiATTextProperty {
  text
  textDecoration
  color
  metaColor
  metaStyle
  fontSize
  fontStyle
  fontWeight
}

fragment plaqueLinkProperty on TaxiATLinkProperty {
  description {
    __typename
    ...plaqueTextProperty
  }
  link
}

fragment plaqueImageProperty on TaxiATImageProperty {
  color
  metaColor
  verticalAlignment
  imageTag
  width
  height
}

fragment plaqueProperty on TaxiATProperty {
  __typename
  ... on TaxiATTextProperty {
    __typename
    ...plaqueTextProperty
  }
  ... on TaxiATLinkProperty {
    __typename
    ...plaqueLinkProperty
  }
  ... on TaxiATImageProperty {
    __typename
    ...plaqueImageProperty
  }
}

fragment plaqueContainer on TaxiATContainer {
  metaColor
  items {
    __typename
    ...plaqueProperty
  }
}

fragment plaqueUnit on TaxiATUnit {
  __typename
  ... on TaxiATTextProperty {
    __typename
    ...plaqueTextProperty
  }
  ... on TaxiATLinkProperty {
    __typename
    ...plaqueLinkProperty
  }
  ... on TaxiATImageProperty {
    __typename
    ...plaqueImageProperty
  }
  ... on TaxiATContainer {
    __typename
    ...plaqueContainer
  }
}

fragment plaqueTextWidget on TextWidget {
  text {
    items {
      __typename
      ...plaqueUnit
    }
  }
  lineHeight
}

fragment plaqueBalanceWidget on BalanceWidget {
  title {
    items {
      __typename
      ...plaqueUnit
    }
  }
  subtitle {
    items {
      __typename
      ...plaqueUnit
    }
  }
  balance {
    items {
      __typename
      ...plaqueUnit
    }
  }
}

fragment plaqueButtonWidget on ButtonWidget {
  text {
    items {
      __typename
      ...plaqueUnit
    }
  }
}

fragment plaqueSwitchWidget on SwitchWidget {
  text {
    items {
      __typename
      ...plaqueUnit
    }
  }
}

fragment plaqueIconWidget on IconWidget {
  image
}

fragment plaqueWidget on CrossWidget {
  widgetId
  contentDescription {
    __typename
    ...plaqueContentDescription
  }
  templates
  strictAction {
    __typename
    ...strictPlaqueAction
  }
  displayWidgetRules {
    __typename
    ...plaqueWidgetRules
  }
  type
  textWidget {
    __typename
    ...plaqueTextWidget
  }
  balanceWidget {
    __typename
    ...plaqueBalanceWidget
  }
  buttonWidget {
    __typename
    ...plaqueButtonWidget
  }
  switchWidget {
    __typename
    ...plaqueSwitchWidget
  }
  iconWidget {
    __typename
    ...plaqueIconWidget
  }
}

fragment widgetGroupWidth on Width {
  __typename
  ... on FillWidth {
    __typename
  }
  ... on FitWidth {
    __typename
  }
  ... on FixWidth {
    fix
  }
}

fragment groupDisplayRules on WidgetGroupDisplayRules {
  indentRules {
    __typename
    ...plaqueIndent
  }
  backgroundColorSettings {
    __typename
    ...plaqueColorSettings
  }
  backgroundShapeSettings {
    __typename
    ...plaqueShapeSettings
  }
  width {
    __typename
    ...widgetGroupWidth
  }
}

fragment typedWidgetGroupProperties on TypedCrossWidgetGroupProperties {
  __typename
  ... on RowCrossWidgetGroupProperties {
    verticalContentAlignment
  }
  ... on ColumnCrossWidgetGroupProperties {
    horizontalContentAlignment
  }
  ... on BoxCrossWidgetGroupProperties {
    horizontalContentAlignment
    verticalContentAlignment
  }
}

fragment plaqueWidgetGroup on CrossWidgetGroup {
  widgetGroupId
  widgets
  groupDisplayRules {
    __typename
    ...groupDisplayRules
  }
  typedProperties {
    __typename
    ...typedWidgetGroupProperties
  }
  strictAction {
    __typename
    ...strictPlaqueAction
  }
  contentDescription {
    __typename
    ...plaqueContentDescription
  }
}

fragment plaqueLevelElement on ElementLevel {
  widgetId
  widgetGroupId
  type
}

fragment plaqueWidgetsLevel on CrossWidgetsLevel {
  widgetsLevelId
  contentDescription {
    __typename
    ...plaqueContentDescription
  }
  elements {
    __typename
    ...plaqueLevelElement
  }
  displayRules {
    __typename
    ...plaqueDisplayRules
  }
  strictAction {
    __typename
    ...strictPlaqueAction
  }
}

fragment plaquePredicate on CommonPredicate {
  type
  argCheckingPredicate {
    type
    argName
  }
  booleanLiteralPredicate {
    value
  }
  notPredicate {
    nodeId
  }
  unifyingPredicate {
    type
    nodeIds
  }
  comparisonPredicate {
    type
    argName
    intValue
    doubleValue
    stringValue
  }
  containsPredicate {
    argName
    intValue
    stringValue
  }
  inSetPredicate {
    argName
    intSet
    stringSet
  }
}

fragment plaquePredicateTree on PredicateTree {
  rootNodeId
  nodes {
    __typename
    ...plaquePredicate
  }
}

fragment plaqueMetric on MetricContext {
  metrics {
    name
    value
  }
}

fragment plaqueIconNotification on IconPlaqueNotification {
  url
  displayRules {
    __typename
    ... on PlaqueNotificationDisplayRules {
      position
    }
  }
}

fragment plaqueCounterNotification on CounterPlaqueNotification {
  count
  displayRules {
    __typename
    ... on PlaqueNotificationDisplayRules {
      position
    }
  }
}

fragment plaque on CrossPlaque {
  plaqueId
  priority
  widgetsLevelIds
  contentDescription {
    __typename
    ...plaqueContentDescription
  }
  condition {
    __typename
    ...plaquePredicateTree
  }
  displayRules {
    __typename
    ...plaqueDisplayRules
  }
  strictAction {
    __typename
    ...strictPlaqueAction
  }
  metricContext {
    __typename
    ...plaqueMetric
  }
  params {
    showAfter
    closeAfter
  }
  seenContext
  notification {
    __typename
    ...plaqueIconNotification
    ...plaqueCounterNotification
  }
  serviceMeta
}

fragment plaqueDefinitions on CrossPlaqueDefinitions {
  widgets {
    __typename
    ...plaqueWidget
  }
  widgetGroups {
    __typename
    ...plaqueWidgetGroup
  }
  widgetsLevels {
    __typename
    ...plaqueWidgetsLevel
  }
  plaques {
    __typename
    ...plaque
  }
  prefetchPlaque {
    __typename
    ...plaque
  }
  defaultPlaque {
    __typename
    ...plaque
  }
  fallbackPlaque {
    __typename
    ...plaque
  }
}
