query SearchMobileShowcase(
  $firstFeaturedCategoryId: Int!
  $includeFirstFeaturedCategory: Boolean!
  $secondFeaturedCategoryId: Int!
  $includeSecondFeaturedCategory: Boolean!
  $featuredCategoryLimit: Int!
  $includeMovieListMetaTotal: Boolean!
  $includeCategories: Boolean!
  $includePopularPersons: Boolean!
  $includeBornTodayPersons: Boolean!
  $birthDate: MonthDayInput!
  $popularPersonsLimit: Int!
  $bornTodayPersonsLimit: Int!
  $includeMoviesSelection: Boolean!
  $moviesSelectionId: String!
  $moviesSelectionLimit: Int!
  $includeMovieRating: Boolean!
  $includeMovieTop250: Boolean!
  $includePlannedToWatchRating: Boolean!
  $includeMovieUserData: Boolean!
  $includeTrialCutInfo: Boolean!
  $includeMoviePurchaseOptions: Boolean!
  $includeMovieOnlyClientSupportedContentFeatures: Boolean
  $includeTVMovieSummary: Boolean!
  $purchaseOptionsContext: BillingFeatureClientContextInput!
) {
  firstFeaturedCategory: movieListCategory(id: $firstFeaturedCategoryId)
    @include(if: $includeFirstFeaturedCategory) {
    __typename
    ...searchShowcaseFeaturedCategoryFragment
  }
  secondFeaturedCategory: movieListCategory(id: $secondFeaturedCategoryId)
    @include(if: $includeSecondFeaturedCategory) {
    __typename
    ...searchShowcaseFeaturedCategoryFragment
  }
  movieListCategories: movieListCategories @include(if: $includeCategories) {
    offset
    limit
    total
    items {
      __typename
      ...movieListCategoryFragment
    }
  }
  selection(id: $moviesSelectionId) @include(if: $includeMoviesSelection) {
    __typename
    ... on CinemaMoviesSelection {
      id
      content(limit: $moviesSelectionLimit) {
        __typename
        ...showcaseSelectionPagingMetaFragment
        items {
          __typename
          ...showcaseCinemaMovieSelectionItemFragment
        }
      }
    }
  }
  popularPersons: popularPersons(limit: $popularPersonsLimit)
    @include(if: $includePopularPersons) {
    offset
    limit
    total
    items {
      person {
        __typename
        ...personSummaryFragment
      }
    }
  }
  personsByBirthDate: personsByBirthDate(
    birthDate: $birthDate
    limit: $bornTodayPersonsLimit
  ) @include(if: $includeBornTodayPersons) {
    offset
    limit
    total
    items {
      person {
        __typename
        ...personSummaryFragment
      }
    }
  }
}

fragment movieListCategoryFragment on MovieListCategory {
  id
  name
}

fragment imageFragment on Image {
  avatarsUrl
  fallbackUrl
}

fragment movieListMetaBaseFragment on MovieListMeta {
  id
  autoList
  name
  description
  url
  cover {
    __typename
    ...imageFragment
  }
  moviesCount: movies(offset: 0, limit: 0)
    @include(if: $includeMovieListMetaTotal) {
    total
  }
}

fragment movieListMetaWithLegacyFiltersFragment on MovieListMeta {
  __typename
  ...movieListMetaBaseFragment
  filterQuery {
    countryId
    excludeViewed
    genreId
    onlyHighRated
    onlyReleased
    onlyTop
    origin
    type
    viewOption
    years {
      start
      end
    }
  }
}

fragment searchShowcaseFeaturedCategoryFragment on MovieListCategory {
  __typename
  ...movieListCategoryFragment
  movieLists(limit: $featuredCategoryLimit, offset: 0) {
    offset
    limit
    total
    items {
      __typename
      ...movieListMetaWithLegacyFiltersFragment
    }
  }
}

fragment showcaseSelectionPagingMetaFragment on SessionPagingList_SelectionItem {
  sessionId
  offset
  limit
  hasMore
}

fragment titleFragment on Title {
  localized
  original
}

fragment genreFragment on Genre {
  id
  name
}

fragment ratingValueFragment on RatingValue {
  isActive
  count
  value(precision: 1)
}

fragment ratingFragment on Rating {
  kinopoisk {
    __typename
    ...ratingValueFragment
  }
  plannedToWatch @include(if: $includePlannedToWatchRating) {
    __typename
    ...ratingValueFragment
  }
}

fragment movieTopsFragment on Movie {
  ratingLists {
    top10 {
      position
      movieListSlug
    }
    top250 @include(if: $includeMovieTop250) {
      position
      movieListSlug
    }
  }
}

fragment movieViewOptionPurchasedSubscriptionFragment on ViewOption {
  purchasedSubscriptionTextId
  purchasedSubscriptionName
}

fragment availabilityAnnounceFragment on AvailabilityAnnounce {
  announcePromise
  availabilityDate
  type
}

fragment movieContentPackageFragment on ContentPackage {
  billingFeatureName
}

fragment currencyFragment on Currency {
  symbol
  currencyCode
}

fragment moneyAmountFragment on MoneyAmount {
  amount
  currency {
    __typename
    ...currencyFragment
  }
}

fragment movieViewOptionTrialCutInfoFragment on TrialCutInfo {
  texts {
    title
    subTitle
    buttonText
  }
  token
  type
}

fragment movieViewOptionSummaryFragment on ViewOption {
  __typename
  type
  purchasabilityStatus
  isWatchableOnDeviceInCurrentRegion: isWatchable(
    filter: { anyDevice: false, anyRegion: false }
  )
  buttonText
  ...movieViewOptionPurchasedSubscriptionFragment
  availabilityAnnounce {
    __typename
    ...availabilityAnnounceFragment
  }
  contentPackageToBuy {
    __typename
    ...movieContentPackageFragment
  }
  contentPackageToUnfreeze {
    __typename
    ...movieContentPackageFragment
  }
  transactionalPrice {
    __typename
    ...moneyAmountFragment
  }
  transactionalMinimumPrice {
    __typename
    ...moneyAmountFragment
  }
  priceWithTotalDiscount {
    __typename
    ...moneyAmountFragment
  }
  optionMonetizationModels
  watchabilityStatus
  watchabilityExpirationTime
  promotionActionType
  downloadabilityStatus
  purchaseOptions(clientContext: $purchaseOptionsContext)
    @include(if: $includeMoviePurchaseOptions) {
    billingFeatureNames
    target
  }
  trialCutInfo @include(if: $includeTrialCutInfo) {
    __typename
    ...movieViewOptionTrialCutInfoFragment
  }
  purchaseOptionCustomProperties @include(if: $includeMoviePurchaseOptions)
}

fragment movieContentFeaturesFragment on Ott {
  preview {
    features(
      filter: {
        layout: OTT_TITLE_CARD
        onlyClientSupported: $includeMovieOnlyClientSupportedContentFeatures
      }
    ) {
      group
      alias
      displayName
    }
  }
}

fragment baseMoviePostersFragment on MoviePosters {
  vertical(override: OTT_WHEN_EXISTS) {
    __typename
    ...imageFragment
  }
  verticalWithRightholderLogo {
    __typename
    ...imageFragment
  }
  horizontal {
    __typename
    ...imageFragment
  }
  horizontalWithRightholderLogo {
    __typename
    ...imageFragment
  }
}

fragment movieIntroPostersFragment on MoviePosters {
  verticalIntro {
    __typename
    ...imageFragment
  }
  verticalIntroWithRightholderLogo {
    __typename
    ...imageFragment
  }
  horizontalIntro {
    __typename
    ...imageFragment
  }
  horizontalIntroWithRightholderLogo {
    __typename
    ...imageFragment
  }
}

fragment moviePostersFragment on MoviePosters {
  __typename
  ...baseMoviePostersFragment
  ...movieIntroPostersFragment
}

fragment imageWithSizeFragment on Image {
  __typename
  ...imageFragment
  origSize {
    width
    height
  }
}

fragment licenseCoverFragment on LicenseCover {
  formFactor
  image {
    __typename
    ...imageFragment
  }
  theme
}

fragment countryFragment on Country {
  id
  name
}

fragment restrictionFragment on Restriction {
  age
  mpaa
}

fragment movieYearsFragment on Movie {
  __typename
  ... on VideoInterface {
    productionYear(override: OTT_WHEN_EXISTS)
  }
  ... on Series {
    fallbackYear: productionYear
    releaseYears {
      start
      end
    }
  }
}

fragment showcaseTVMovieSummaryFragment on Movie {
  __typename
  id
  contentId
  title {
    __typename
    ...titleFragment
  }
  ott {
    __typename
    ...movieContentFeaturesFragment
    preview {
      __typename
      ... on OttPreview_AbstractVideo {
        duration
      }
    }
  }
  gallery {
    posters {
      __typename
      ...moviePostersFragment
    }
    logos {
      horizontal {
        __typename
        ...imageWithSizeFragment
      }
      rightholderForCover(filter: { formFactor: M }) {
        __typename
        ...licenseCoverFragment
      }
      rightholderForCoverRecommendedTheme
    }
    covers {
      horizontal {
        __typename
        ...imageFragment
      }
    }
  }
  genres {
    __typename
    ...genreFragment
  }
  countries {
    __typename
    ...countryFragment
  }
  editorAnnotation
  restriction {
    __typename
    ...restrictionFragment
  }
  rating @include(if: $includeMovieRating) {
    __typename
    ...ratingFragment
  }
  ...movieTopsFragment
  shortDescription
  ... on TvSeries {
    seasons {
      total
    }
  }
  ...movieYearsFragment
}

fragment showcaseBaseMovieFragment on Movie {
  __typename
  id
  contentId
  title {
    __typename
    ...titleFragment
  }
  genres {
    __typename
    ...genreFragment
  }
  rating @include(if: $includeMovieRating) {
    __typename
    ...ratingFragment
  }
  ...movieTopsFragment
  viewOption {
    __typename
    ...movieViewOptionSummaryFragment
  }
  ...showcaseTVMovieSummaryFragment @include(if: $includeTVMovieSummary)
}

fragment showcaseMovieFragment on Movie {
  __typename
  ...showcaseBaseMovieFragment
  gallery {
    posters {
      __typename
      ...baseMoviePostersFragment
    }
  }
  ...showcaseTVMovieSummaryFragment @include(if: $includeTVMovieSummary)
}

fragment showcaseCinemaMovieSelectionItemFragment on CinemaMovieSelectionItem {
  movie {
    __typename
    ...showcaseMovieFragment
    userData @include(if: $includeMovieUserData) {
      isPlannedToWatch
    }
    ticketOption {
      purchasable
    }
  }
}

fragment personNameFragment on Person {
  name
  originalName
}

fragment incompleteDateFragment on IncompleteDate {
  date
  accuracy
}

fragment personSummaryFragment on Person {
  __typename
  id
  ...personNameFragment
  gender
  poster {
    __typename
    ...imageFragment
  }
  age
  height
  dateOfBirth {
    __typename
    ...incompleteDateFragment
  }
  dateOfDeath {
    __typename
    ...incompleteDateFragment
  }
  published
}
