query SportWatchingFriends(
  $sportEventId: String!
  $friendsSportReactionsLimit: Int!
  $friendsSportReactionsOffset: Int!
  $includeVerification: Boolean!
) {
  sportEvent(sportEventId: $sportEventId) {
    watchingSportSocialArgument {
      socialSubscriptionsWatching(
        limit: $friendsSportReactionsLimit
        offset: $friendsSportReactionsOffset
      ) {
        limit
        offset
        total
        items {
          __typename
          ...sportWatchingUserInfoFragment
        }
      }
    }
  }
}

fragment imageFragment on Image {
  avatarsUrl
  fallbackUrl
}

fragment socialInfoFragment on UserSocialInfo {
  alias {
    defaultValue {
      value
      source
    }
  }
  name {
    defaultValue {
      value
    }
  }
  avatar {
    defaultValue {
      value {
        __typename
        ...imageFragment
      }
    }
  }
  publicStatus
  url
  badges @include(if: $includeVerification) {
    verified {
      id
      title
      description
      icons {
        format
        image {
          __typename
          ...imageFragment
        }
      }
    }
  }
}

fragment sportWatchingUserInfoFragment on UserProfileInterface {
  subscriptionInfo {
    hasSubscription
  }
  id {
    puid
  }
  social {
    __typename
    ...socialInfoFragment
  }
}
