query StreamsDownloadableStreams(
  $contentId: String!
  $downloadId: String
  $prerollsSupported: Boolean!
  $includeWatchParams: Boolean!
  $includeTiming: Boolean!
  $includeLogo: Boolean! = false
  $includeMyShowsComments: Boolean! = false
  $includeEstEarlyAccess: Boolean! = false
) {
  content(contentId: $contentId) {
    __typename
    ... on Movie {
      __typename
      ...streamsMovieDownloadableStreamsFragment
    }
    ... on Episode {
      __typename
      ...streamsNextEpisodeAvailability
      ...streamsEpisodeDownloadableStreamsFragment
    }
  }
}

fragment titleFragment on Title {
  localized
  original
}

fragment imageFragment on Image {
  avatarsUrl
  fallbackUrl
}

fragment restrictionFragment on Restriction {
  age
  mpaa
}

fragment streamsOttWatchParamsFragment on Ott {
  userData {
    watchParams {
      audioLanguage
      subtitleLanguage
    }
  }
}

fragment streamsWatchParamsFragment on Movie {
  ott {
    __typename
    ...streamsOttWatchParamsFragment
  }
}

fragment myShowsCommentsFragment on MyShowsComments {
  __typename
  url
  count
  rawCount
}

fragment movieCommentsFragment on Movie {
  myShowsComments @include(if: $includeMyShowsComments) {
    __typename
    ...myShowsCommentsFragment
  }
}

fragment streamsMovieMetaFragment on Movie {
  __typename
  id
  contentId
  title {
    __typename
    ...titleFragment
  }
  editorAnnotation
  gallery @include(if: $includeLogo) {
    logos {
      horizontal {
        __typename
        ...imageFragment
      }
    }
  }
  restriction {
    __typename
    ...restrictionFragment
  }
  ...streamsWatchParamsFragment @include(if: $includeWatchParams)
  ...movieCommentsFragment
}

fragment movieFilmOttWatchProgressFragment on Ott {
  preview {
    __typename
    ... on OttPreview_AbstractVideo {
      duration
      timing @include(if: $includeTiming) {
        current
      }
    }
  }
}

fragment movieStreamsAudioMetaFragment on AudioMeta {
  audioChannelsNumber
  audioGroupId
  forAdult
  language
  languageName
  quality
  qualityName
  studio
  type
  visibleByDefault
}

fragment streamsVideoMetaFragment on VideoMeta {
  bitrate
  codec
  dynamicRange
  framesPerSecond
  height
  width
  label
}

fragment movieStreamsSubtitleMetaFragment on SubtitleMeta {
  forAdult
  language
  languageName
  studio
  type
  visibleByDefault
}

fragment streamsDrmMetaFragment on StreamMeta {
  drmConfig {
    drmServers {
      certificateUrl
      name
      processSPCPath
      provisioningUrl
      url
    }
    headers
    requestParams
  }
}

fragment streamsMetaFragment on StreamMeta {
  __typename
  audioMetas {
    __typename
    ...movieStreamsAudioMetaFragment
  }
  cuesUrl
  videoMetas {
    __typename
    ...streamsVideoMetaFragment
  }
  subtitleMetas {
    __typename
    ...movieStreamsSubtitleMetaFragment
  }
  prerollsDuration
  prerolls {
    durationMs
    promotedEntityId
    sourceMeta {
      __typename
      ... on PrerollNotificationMeta {
        communicationId
        notificationId
        feedbackToken
      }
    }
  }
  videoToken
  clearStreamEncoding
  ...streamsDrmMetaFragment
  skippableFragments {
    endTime
    final
    startTime
    type
  }
  trackings
  disclaimers {
    type
  }
}

fragment streamsStreamItemFragment on Stream {
  drmType
  streamType
  uri
  videoDescriptorName
  streamMeta {
    __typename
    ...streamsMetaFragment
  }
}

fragment streamsDownloadableStreamsFragment on DownloadableStreams {
  downloadId
  downloadLicenseId
  drmRequirement
  monetizationModel
  playerRestrictionConfig {
    subtitlesButtonEnable
  }
  sessionId
  streams {
    __typename
    ...streamsStreamItemFragment
  }
}

fragment streamsMovieDownloadableStreamsFragment on Movie {
  __typename
  ...streamsMovieMetaFragment
  ott {
    __typename
    ...movieFilmOttWatchProgressFragment
    ... on Ott_AbstractVideo {
      hasSmokingScenes
      downloadableStreams(
        downloadId: $downloadId
        prerollsSupported: $prerollsSupported
      ) {
        __typename
        ...streamsDownloadableStreamsFragment
      }
    }
  }
}

fragment currencyFragment on Currency {
  symbol
  currencyCode
}

fragment moneyAmountFragment on MoneyAmount {
  amount
  currency {
    __typename
    ...currencyFragment
  }
}

fragment availabilityAnnounceFragment on AvailabilityAnnounce {
  announcePromise
  availabilityDate
  type
}

fragment estEarlyAccessViewOptionFragment on Episode {
  viewOption {
    watchabilityStatus
    purchasabilityStatus
    optionMonetizationModels
    transactionalPrice {
      __typename
      ...moneyAmountFragment
    }
    availabilityAnnounce {
      __typename
      ...availabilityAnnounceFragment
    }
  }
}

fragment streamsNextEpisodeAvailability on Episode {
  neighbourhoodInSeries(filter: { onlyOnline: true }, limit: 1) {
    items {
      __typename
      contentId
      tvSeries {
        contentId
      }
      ott {
        viewOption {
          watchabilityStatus
        }
      }
      ...estEarlyAccessViewOptionFragment @include(if: $includeEstEarlyAccess)
      cover {
        __typename
        ...imageFragment
      }
      episodeTitle: title {
        __typename
        ...titleFragment
      }
    }
  }
}

fragment movieEpisodeOttWatchProgressFragment on OttEpisode {
  duration
  timing @include(if: $includeTiming) {
    current
  }
}

fragment episodeCommentsFragment on Episode {
  myShowsComments @include(if: $includeMyShowsComments) {
    __typename
    ...myShowsCommentsFragment
  }
}

fragment streamsEpisodeMetaFragment on Episode {
  __typename
  id
  contentId
  number
  season {
    number
  }
  title {
    __typename
    ...titleFragment
  }
  tvSeries {
    __typename
    ...streamsMovieMetaFragment
  }
  ottEpisode: ott {
    __typename
    ...movieEpisodeOttWatchProgressFragment
  }
  ...episodeCommentsFragment
}

fragment streamsEpisodeDownloadableStreamsFragment on Episode {
  __typename
  ...streamsEpisodeMetaFragment
  ottEpisode: ott {
    hasSmokingScenes
    downloadableStreams(
      downloadId: $downloadId
      prerollsSupported: $prerollsSupported
    ) {
      __typename
      ...streamsDownloadableStreamsFragment
    }
  }
}
