query UserProfileBackgrounds {
  userProfile {
    ...SocialUserProfileId
    social {
      preparedBackgrounds(limit: 100) {
        items {
          ...UserProfileBackgroundsItem
          __typename
        }
        total
        __typename
      }
      __typename
    }
    __typename
  }
}

fragment SocialUserProfileId on UserProfileInterface {
  id {
    kpId
    ottId
    puid
    __typename
  }
  __typename
}

fragment UserProfileBackgroundsItem on PreparedProfileBackground {
  id
  image {
    avatarsUrl
    __typename
  }
  __typename
}
