query VerticalSeriesStream($contentId: String!, $includeTiming: Boolean!) {
  content(contentId: $contentId) {
    __typename
    ...verticalSeriesContentFragment
  }
}

fragment imageFragment on Image {
  avatarsUrl
  fallbackUrl
}

fragment movieEpisodeOttWatchProgressFragment on OttEpisode {
  duration
  timing @include(if: $includeTiming) {
    current
  }
}

fragment movieStreamsAudioMetaFragment on AudioMeta {
  audioChannelsNumber
  audioGroupId
  forAdult
  language
  languageName
  quality
  qualityName
  studio
  type
  visibleByDefault
}

fragment streamsVideoMetaFragment on VideoMeta {
  bitrate
  codec
  dynamicRange
  framesPerSecond
  height
  width
  label
}

fragment movieStreamsSubtitleMetaFragment on SubtitleMeta {
  forAdult
  language
  languageName
  studio
  type
  visibleByDefault
}

fragment streamsDrmMetaFragment on StreamMeta {
  drmConfig {
    drmServers {
      certificateUrl
      name
      processSPCPath
      provisioningUrl
      url
    }
    headers
    requestParams
  }
}

fragment streamsMetaFragment on StreamMeta {
  __typename
  audioMetas {
    __typename
    ...movieStreamsAudioMetaFragment
  }
  cuesUrl
  videoMetas {
    __typename
    ...streamsVideoMetaFragment
  }
  subtitleMetas {
    __typename
    ...movieStreamsSubtitleMetaFragment
  }
  prerollsDuration
  prerolls {
    durationMs
    promotedEntityId
    sourceMeta {
      __typename
      ... on PrerollNotificationMeta {
        communicationId
        notificationId
        feedbackToken
      }
    }
  }
  videoToken
  clearStreamEncoding
  ...streamsDrmMetaFragment
  skippableFragments {
    endTime
    final
    startTime
    type
  }
  trackings
  disclaimers {
    type
  }
}

fragment streamsStreamItemFragment on Stream {
  drmType
  streamType
  uri
  videoDescriptorName
  streamMeta {
    __typename
    ...streamsMetaFragment
  }
}

fragment streamsOnlineStreamsFragment on OnlineStreams {
  concurrencyArbiterConfig {
    concurrencyArbiterRequestParams
    server
  }
  drmRequirement
  monetizationModel
  playerRestrictionConfig {
    dvrSeconds
    subtitlesButtonEnable
  }
  sessionId
  streams {
    __typename
    ...streamsStreamItemFragment
  }
}

fragment verticalSeriesStreamFragment on Stream {
  streamType
  uri
  drmType
  streamMeta {
    __typename
    trackings
    disclaimers {
      type
    }
    videoToken
    ...streamsDrmMetaFragment
    audioMetas {
      __typename
      ...movieStreamsAudioMetaFragment
    }
    subtitleMetas {
      __typename
      ...movieStreamsSubtitleMetaFragment
    }
  }
}

fragment verticalSeriesContentFragment on Content {
  __typename
  ... on Episode {
    cover {
      __typename
      ...imageFragment
    }
    ott {
      __typename
      ...movieEpisodeOttWatchProgressFragment
      onlineStreams {
        __typename
        sessionId
        ...streamsOnlineStreamsFragment
        streams {
          __typename
          ...verticalSeriesStreamFragment
        }
      }
    }
  }
  ... on OttTrailer {
    streams {
      __typename
      ...verticalSeriesStreamFragment
    }
  }
}
