mutation CreateInvoice(
  $eventSessionId: String!
  $tariffId: OfferNameScalar
  $optionsIds: [OfferNameScalar!]!
  $offerFor: OfferNameScalar
  $language: TRANSITION_LANGUAGE!
  $origin: String!
  $paymentMethodId: String
  $returnPath: URLScalar!
  $source: String!
  $target: String!
  $templateTag: TEMPLATE_TAG!
  $developerPayload: String!
  $offersPositionId: String!
  $offersBatchId: String!
  $externalCallerPayload: String!
  $silentRequested: Boolean!
  $experimentFlags: [String!]
  $additionalOffers: CheckoutInvoiceAdditionalOffersInput
) {
  invoice {
    externalCreate(
      eventSessionId: $eventSessionId
      req: {
        offersPositionId: $offersPositionId
        offersBatchId: $offersBatchId
        compositeOffer: {
          tariffOffer: $tariffId
          serviceOffers: $optionsIds
          offerFor: $offerFor
        }
        developerPayload: $developerPayload
        language: $language
        origin: $origin
        paymentMethodId: $paymentMethodId
        returnPath: $returnPath
        source: $source
        target: $target
        templateTag: $templateTag
        externalCallerPayload: $externalCallerPayload
        oneClickRequested: $silentRequested
        experimentFlags: $experimentFlags
        additionalOffers: $additionalOffers
      }
    ) {
      __typename
      ...invoice
    }
  }
}

fragment invoicePrice on Price {
  currency
  amount
}

fragment invoicePayment on Payment {
  id
  respCode
  respDesc
  status
}

fragment invoice on Invoice {
  id
  invoiceStatus
  form
  paymentMethodId
  paidAmount {
    __typename
    ...invoicePrice
  }
  payment {
    __typename
    ...invoicePayment
  }
  totalAmount {
    __typename
    ...invoicePrice
  }
  invoicePollingParams {
    retryDelayMillis
    timeoutMillis
  }
  widgetQrCodeParams {
    widgetUrl
    underlineText
  }
}
